# Generated by Django 4.0.1 on 2022-01-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
            ],
        ),
    ]
