# Generated by Django 4.0.1 on 2022-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_wordpool_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpool',
            name='original_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
