# Generated by Django 4.0.1 on 2022-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_failpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='failpool',
            name='answers',
            field=models.CharField(choices=[('a1', 'test'), ('a2', 'test2')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='failpool',
            name='question',
            field=models.CharField(default='', max_length=50),
        ),
    ]
