# Generated by Django 4.0.1 on 2022-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_rename_failpool_answeredpool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeredpool',
            old_name='question',
            new_name='failed_question',
        ),
        migrations.RemoveField(
            model_name='answeredpool',
            name='failed_questions',
        ),
        migrations.AddField(
            model_name='answeredpool',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
