# Generated by Django 4.0.1 on 2022-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_rename_question_answeredpool_failed_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeredpool',
            old_name='failed_question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answeredpool',
            name='answers',
            field=models.CharField(default='', max_length=50),
        ),
    ]
