# Generated by Django 4.0.1 on 2022-01-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_rename_failed_question_answeredpool_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeredpool',
            old_name='answers',
            new_name='answer',
        ),
    ]
