# Generated by Django 4.0.1 on 2022-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_rename_answers_answeredpool_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredpool',
            name='answer',
            field=models.CharField(max_length=50),
        ),
    ]
